'use client';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { cases, source } from '@/data/cases';
import { hints, phases, sarachiOriginal } from '@/data/learning';
import sarachiArt from '@/public/art/sarachi.png';

type Records = Record<string, number>;
type View = 'home' | 'quests' | 'play' | 'collection' | 'notebook' | 'finish';
function Character({className=''}:{className?:string}) {return <Image className={`character ${className}`} src={sarachiArt} alt="更地の精霊。白い花、緑と白の衣装、紅白の測量杖を持つ案内役" priority sizes="(max-width: 700px) 70vw, 600px"/>;}
export default function Home() {
 const [view,setView]=useState<View>('home');
 const [order,setOrder]=useState([0,1,2,3]); const [pos,setPos]=useState(0);
 const [phase,setPhase]=useState(0); const [revealed,setRevealed]=useState([false,false]);
 const [answers,setAnswers]=useState([-1,-1,-1]); const [records,setRecords]=useState<Records>({});
 const [unlocked,setUnlocked]=useState(false); const [newReward,setNewReward]=useState(false);
 const [total,setTotal]=useState(0); const [round,setRound]=useState<Records>({});
 const [detail,setDetail]=useState(false); const [review,setReview]=useState(false);
 const [speaking,setSpeaking]=useState(false); const [notice,setNotice]=useState('');
 const [voiceNotice,setVoiceNotice]=useState(''); const [ready,setReady]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null); const voiceGeneration=useRef(0);
 const c=cases[order[pos]]; const qi=phase-1;
 const correct=c.questions.reduce((sum,q,i)=>sum+(answers[i]===q.correct?1:0),0);
 const xp=Object.values(records).reduce((a,b)=>a+b*100,0);
 const mastered=Object.values(records).filter(n=>n===3).length;
 useEffect(()=>{try {const saved=JSON.parse(localStorage.getItem('kantei-quest-v2')||'null');const old=saved?.records??JSON.parse(localStorage.getItem('kantei-atlas-v1')||'{}');const valid:Records={};for(const item of cases)if(Number.isInteger(old?.[item.id])&&old[item.id]>=0&&old[item.id]<=3)valid[item.id]=old[item.id];setRecords(valid);setUnlocked(saved?.unlocked===true);}catch{setNotice('この環境では記録を保存できません。今回のプレイは続けられます。');}setReady(true);return()=>{window.speechSynthesis?.cancel();};},[]);
 useEffect(()=>{heading.current?.focus({preventScroll:true});},[phase,view,pos]);
 function stop(){voiceGeneration.current++;window.speechSynthesis?.cancel();setSpeaking(false);}
 function navigate(next:View){stop();setVoiceNotice('');setDetail(false);setView(next);window.scrollTo({top:0});}
 function resetCase(){setPhase(0);setRevealed([false,false]);setAnswers([-1,-1,-1]);setDetail(false);setReview(false);setNewReward(false);setVoiceNotice('');}
 function start(list=[0,1,2,3]){stop();setOrder(list.length?list:[0,1,2,3]);setPos(0);setTotal(0);setRound({});resetCase();setView('play');window.scrollTo({top:0});}
 function startReview(){start(cases.map((_,i)=>i).filter(i=>(records[cases[i].id]??0)<3));}
 function save(){const next={...records,[c.id]:Math.max(records[c.id]??0,correct)};const earned=c.id==='sarachi'&&correct>=2;const nextUnlocked=unlocked||earned;setNewReward(earned&&!unlocked);setUnlocked(nextUnlocked);setRecords(next);setRound(r=>({...r,[c.id]:correct}));setTotal(t=>t+correct);try{localStorage.setItem('kantei-quest-v2',JSON.stringify({records:next,unlocked:nextUnlocked}));}catch{setNotice('記録を保存できませんでした。今回の結果は画面で確認できます。');}}
 function confirm(){if(phase<1||phase>3||answers[qi]<0)return;stop();if(phase===3)save();setPhase(p=>p+1);}
 function nextCase(){stop();if(pos===order.length-1){setView('finish');}else{setPos(p=>p+1);resetCase();}window.scrollTo({top:0});}
 function speak(text:string){if(speaking){stop();return;}if(!('speechSynthesis' in window)){setVoiceNotice('このブラウザは読み上げ非対応です。表示された文章で復習できます。');return;}stop();const generation=voiceGeneration.current;const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.85;const voice=window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('ja'));if(voice)u.voice=voice;u.onend=()=>{if(generation===voiceGeneration.current)setSpeaking(false);};u.onerror=()=>{if(generation===voiceGeneration.current){setSpeaking(false);setVoiceNotice('日本語音声を再生できませんでした。下の文章で復習できます。');}};setVoiceNotice('');setSpeaking(true);window.speechSynthesis.speak(u);}
 const voiceButton=(text:string,label:string)=><button className="parchment-button" onClick={()=>speak(text)}>{speaking?'■ 停止':`♬ ${label}`}</button>;
 const questCards=<div className="quest-grid">{cases.map((item,i)=><button className={`quest-card quest-${i}`} key={item.id} onClick={()=>start([i])}><span className="quest-number">CASE 0{i+1}</span><span className="quest-symbol">{item.icon}</span><h3>{item.subtitle}</h3><span>{item.district}</span><div className="quest-bottom"><span className="stars" aria-label={`${records[item.id]??0}問習得`}>{'★'.repeat(records[item.id]??0)}{'☆'.repeat(3-(records[item.id]??0))}</span><b>挑戦する ›</b></div></button>)}</div>;
 return <div className="game"><header className="statusbar"><button className="wordmark" onClick={()=>navigate('home')} aria-label="鑑定クエスト ホーム"><span>✧</span> 鑑定クエスト</button><div className="level"><span>Lv.<b>{1+Math.floor(xp/300)}</b></span><div><small>見習い鑑定士</small><div className="xp-track"><i style={{width:`${xp%300/3}%`}}/></div></div></div><span className="currency">✦ <b>{xp.toLocaleString()}</b><small> 知識EXP</small></span><button className="collection-count" onClick={()=>navigate('collection')}>◇ <b>{unlocked?1:0}</b> / 1</button></header>
 {(view==='home'||view==='quests')&&<main className="landing"><section className="home-hero"><div className="hero-shade"/><div className="hero-copy"><span className="chapter-label">第1章 ─ 都市鑑定編</span><h1 ref={heading} tabIndex={-1}>この街の、<br/>まだ見ぬ価値を。</h1><p>知識が力になる。判断が未来を変える。<br/>土地の精霊とともに、鑑定の旅へ。</p><button className="gold-button" disabled={!ready} onClick={()=>start()}>クエストをはじめる <span>❯</span></button><small>4つの案件 / 調査・判断・基準復習</small></div><Character className="hero-character"/><div className="hero-character-name"><span>SSR ✦ 大地の精霊</span><b>更 地</b><small>何もない場所にこそ、無限の可能性がある。</small></div><div className="hero-bottom">✧　土地がつなぐ、人の物語　✧</div></section><section className="quest-section"><div className="section-title"><div><small>CHAPTER 01</small><h2>鑑定クエスト</h2></div><button className="dark-button" onClick={startReview}>未習得を復習 ↻</button></div>{questCards}<div className="reward-banner"><span>✦</span><p><b>初回クリア報酬 ─ SSR 更地</b><small>CASE 01で2問以上正解すると、キャラ図鑑と原文復習を解放。</small></p><button onClick={()=>navigate('collection')}>図鑑へ ›</button></div></section></main>}
 {view==='play'&&<main className={`quest-stage ${c.id==='sarachi'?'station-stage':'abstract-stage'} ${phase===4?'result-stage':''}`}><div className="stage-shade"/><div className="stage-content"><div className="stage-heading"><div><span className="chapter-label">CASE 0{order[pos]+1} <span>・ 調査 {pos+1} / {order.length}</span></span><h1 ref={heading} tabIndex={-1}>{c.subtitle}</h1><p>{c.title}</p></div><button className="dark-button" onClick={()=>setDetail(!detail)} aria-expanded={detail}>▤ 案件詳細</button></div><ol className="phase-track" aria-label="鑑定の進行">{phases.map((p,i)=><li key={p} className={i===phase?'active':i<phase?'done':''} aria-current={i===phase?'step':undefined}><span>{i<phase?'✓':['⌕','◇','▥','⚖','✦'][i]}</span><b>{p}</b></li>)}</ol>
 {detail&&<section className="detail-panel parchment"><h2>今回の評価対象</h2><p>{c.scope}</p><p>資料は「地域分析」「個別分析」を行うと公開されます。</p><p className="small-print">背景は世界観を表すイメージです。道路幅・権利・法規制などは調査資料を判断の根拠にしてください。</p><button className="dark-button" onClick={()=>setDetail(false)}>閉じる</button></section>}
 <div className="scene-space"><span className="location-label">⌖ {c.district} {c.id==='sarachi'?'・ 対象地イメージ':'・ 現地イラスト準備中'}</span>{phase<4&&<div className="evidence-row">{['地域分析の結果','個別分析の結果'].map((label,i)=><section key={label} className={`evidence parchment ${revealed[i]?'revealed':''}`}><h3>{i===0?'▥':'⌕'} {label}</h3>{revealed[i]?<ul>{c.facts.filter((_,j)=>i===0?j===0||j===3:j===1||j===2).map(([key,value])=><li key={key}><b>{key}</b> {value}</li>)}</ul>:<p>下の調査カードで<br/>情報を集めましょう。</p>}</section>)}</div>}</div>
 <div className="action-area"><aside className="companion"><Character className="play-character"/><div className="dialogue parchment"><h2><span>✦</span> 更地 <small>土地の精霊 / 案内役</small></h2><p>{phase===0?'この土地に、どんな未来があるでしょう？ まずは地域と対象不動産を調べましょう。':phase===4?(correct===3?'見事です。根拠を持って、この土地の価値に近づきましたね。':'迷ったところに、学びの種があります。一緒に基準を振り返りましょう。'):hints[qi]}</p></div></aside>
 <section className="command-panel ornate" aria-label="鑑定コマンド">
 {phase===0?<><div className="panel-title"><small>INVESTIGATION</small><h2>価値を見抜く、第一歩。</h2><p>2枚の調査カードを使い、判断材料を集めよう。</p></div><div className="investigation-cards">{['地域分析','個別分析'].map((label,i)=><button key={label} className={`skill-card skill-${i} ${revealed[i]?'used':''}`} aria-pressed={revealed[i]} onClick={()=>setRevealed(r=>r.map((v,j)=>i===j?true:v))}><span>{i===0?'▥':'⌕'}</span><b>{label}</b><small>{revealed[i]?'✓ 調査済み':i===0?'街を読み、需要を知る':'対象地と権利を確かめる'}</small></button>)}</div>{revealed.every(Boolean)&&<div className="survey-note parchment"><b>調査員の総合所見</b><p>{c.memo}</p><p><strong>評価対象：</strong>{c.scope}</p></div>}<button className="gold-button" disabled={!revealed.every(Boolean)} onClick={()=>setPhase(1)}>判断に進む <span>❯</span></button></>:
 phase<4?<><div className="panel-title"><small>JUDGMENT 0{phase} / 03</small><h2>{c.questions[qi].title}</h2></div><details className="survey-toggle"><summary>▤ 総合所見・評価対象を確認</summary><p>{c.memo}</p><p><b>評価対象：</b>{c.scope}</p></details><fieldset className="command-options"><legend className="sr-only">{c.questions[qi].title}</legend>{c.questions[qi].options.map((option,i)=><label key={`${phase}-${i}`} className={`answer-card ${answers[qi]===i?'selected':''}`}><input type="radio" name={`question-${phase}`} checked={answers[qi]===i} onChange={()=>setAnswers(a=>a.map((v,j)=>qi===j?i:v))}/><span className="answer-icon">{['◇','▥','⚖'][i]}</span><span>{option}</span><b>{answers[qi]===i?'✓':''}</b></label>)}</fieldset><div className="active-skill"><span>{['◇','▥','⚖'][qi]}</span><div><b>{phases[phase]}</b><small>知識を使い、根拠ある判断へ。</small></div></div><button className="gold-button" disabled={answers[qi]<0} onClick={confirm}>{phase===3?'鑑定を完了する':'この判断で進む'} <span>❯</span></button><small className="selection-note">採点と解説は、3つの判断が終わった後に表示されます。</small></>:
 <div className="result-content"><div className="result-title"><small>QUEST COMPLETE</small><h2>{correct>=2?'鑑定成功':'調査完了'}</h2><span className="result-stars">{'★'.repeat(correct)}{'☆'.repeat(3-correct)}</span><p><b>{correct} / 3</b> 問正解</p></div>{newReward?<div className="unlock-reward"><span>NEW CHARACTER</span><b>SSR 更地を獲得！</b><p>図鑑で原文を聞いて、いつでも復習できます。</p></div>:<p className="result-note">{c.id==='sarachi'&&!unlocked?'2問以上正解で「SSR 更地」を解放。再挑戦してみましょう。':'判断の根拠を確認して、次の案件へ。'}</p>}<div className="reward-line"><span>今回の学習ポイント</span><b>✦ {correct*100} pt</b></div><button className="parchment-button full" onClick={()=>setReview(!review)} aria-expanded={review}>{review?'基準復習を閉じる':'▤ 解説・基準を復習する'}</button>{review&&<div className="review-block parchment">{c.questions.map((q,i)=><section key={q.title}><h3>{answers[i]===q.correct?'✓ 正解':'↳ 復習'} ・ {phases[i+1]}</h3><b>正解：{q.options[q.correct]}</b><p>{q.explanation}</p></section>)}<h3>{c.id==='sarachi'?'更地の定義【基準原文】':'覚えておきたい要点【要約】'}</h3><p>{c.id==='sarachi'?sarachiOriginal:c.knowledge}</p>{voiceButton(c.id==='sarachi'?sarachiOriginal:c.knowledge,c.id==='sarachi'?'原文を聞く':'要点を聞く')}<a href={`${source}#page=${c.page}`} target="_blank" rel="noreferrer">出典：不動産鑑定評価基準 ↗</a></div>}<button className="gold-button" onClick={nextCase}>{pos===order.length-1?'今回の結果を見る':'次の案件へ'} <span>❯</span></button></div>}
 {voiceNotice&&<p role="status" className="notice">{voiceNotice}</p>}</section></div></div></main>}
 {view==='collection'&&<main className="collection-page"><div className="section-title"><div><small>CHARACTER ARCHIVE</small><h1 ref={heading} tabIndex={-1}>精霊図鑑</h1></div><span>{unlocked?'1':'0'} / 1 解放</span></div><div className="collection-layout"><div className={`portrait ornate ${unlocked?'':'locked'}`}><Character/><span className="rarity">SSR</span><h2>更 地</h2></div><section className="collection-info ornate"><span className="chapter-label">大地が紡ぐ、未来のかたち</span><h2>何もない場所にこそ、<br/>可能性がある。</h2><p>土地の利用と権利を見守る精霊。あなたの鑑定の旅を案内します。</p>{unlocked?<><div className="definition parchment"><h3>更地の定義【基準原文】</h3><p>{sarachiOriginal}</p>{voiceButton(sarachiOriginal,'原文を聞く')}<a href={`${source}#page=9`} target="_blank" rel="noreferrer">総論 第2章 第2節 ↗</a></div><div className="mastery"><span>更地の案件習得</span><b>{records.sarachi??0} / 3</b></div></>:<div className="definition parchment"><h3>解放条件</h3><p>CASE 01「駅近商業地の更地」で2問以上正解。</p></div>}<button className="gold-button" onClick={()=>start([0])}>更地の案件に挑む ❯</button>{voiceNotice&&<p role="status">{voiceNotice}</p>}</section></div></main>}
 {view==='notebook'&&<main className="notebook"><div className="section-title"><div><small>KNOWLEDGE JOURNAL</small><h1 ref={heading} tabIndex={-1}>学習手帳</h1></div><span>習得 {mastered} / 4</span></div><p>各案件の最高成績を記録。3問正解で習得です。</p>{cases.map((item,i)=><section className="journal-entry parchment" key={item.id}><div><span>CASE 0{i+1}</span><h2>{item.subtitle}</h2><span className="stars">{'★'.repeat(records[item.id]??0)}{'☆'.repeat(3-(records[item.id]??0))}</span></div><p>{item.knowledge}</p><button className="dark-button" onClick={()=>start([i])}>この案件を復習 →</button></section>)}<button className="gold-button" onClick={startReview}>未習得の案件に挑む ❯</button></main>}
 {view==='finish'&&<main className="finish ornate"><span className="chapter-label">EXPEDITION COMPLETE</span><h1 ref={heading} tabIndex={-1}>今日の発見が、<br/>明日の判断になる。</h1><div className="finish-score">✦ <strong>{total*100}</strong><span>今回の学習ポイント</span><b>{total} / {order.length*3} 問正解</b></div>{order.map(i=><div className="finish-line" key={i}><span>{cases[i].subtitle}</span><b>{round[cases[i].id]??0} / 3</b></div>)}<button className="gold-button" onClick={startReview}>未習得の案件をもう一度 ❯</button><button className="dark-button" onClick={()=>navigate('collection')}>獲得したキャラを見る</button></main>}
 {notice&&<p role="status" className="save-notice">{notice}</p>}<footer className="footnote">学習用の架空案件です。背景はイメージ。成績は実務の鑑定精度を表しません。<br/>読み上げは端末の音声を使用。原文と要約を区別して表示しています。</footer><nav className="bottom-nav" aria-label="メインメニュー">{([['home','⌂','ホーム'],['quests','✧','クエスト'],['collection','♧','キャラ図鑑'],['notebook','▤','学習手帳']] as const).map(([id,icon,label])=><button key={id} aria-label={label} className={view===id||(id==='quests'&&view==='play')?'active':''} onClick={()=>navigate(id)} aria-current={view===id?'page':undefined}><span>{icon}</span><b>{label}</b></button>)}</nav></div>;
}

